all:
	cd client && make
	cd simpleServer && make
	cd multi_thread_server && make

client:
	cd client && make

clean:
	cd client && make clean
	cd simpleServer && make clean
	cd multi_thread_server && make clean