all:
	cd client && make
	cd simple_server && make
	cd multi_thread_server && make
	cd thread_pool_server && make
	cd thread_pool_priority_server && make

client:
	cd client && make

clean:
	cd client && make clean
	cd simple_server && make clean
	cd multi_thread_server && make clean
	cd thread_pool_server && make clean
	cd thread_pool_priority_server && make clean